# Generated by Django 5.2.11 on 2026-02-25 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('message_hash', models.CharField(blank=True, help_text='SHA-256 of original message for dedup', max_length=64)),
                ('label', models.CharField(choices=[('spam', 'Spam'), ('legitimate', 'Legitimate')], max_length=12)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=8)),
                ('language', models.CharField(default='en', max_length=5)),
                ('mode', models.CharField(choices=[('ml', 'ML Model'), ('rule_based', 'Rule Based')], default='ml', max_length=12)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('spam_probability', models.FloatField(default=0)),
                ('legit_probability', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(max_length=64)),
                ('original_label', models.CharField(max_length=12)),
                ('corrected_label', models.CharField(max_length=12)),
                ('language', models.CharField(default='en', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('language', models.CharField(default='en', max_length=5)),
                ('predicted_label', models.CharField(blank=True, default='', max_length=12)),
                ('sample_message', models.TextField(blank=True, default='')),
                ('first_reported', models.DateTimeField(auto_now_add=True)),
                ('last_reported', models.DateTimeField(auto_now=True)),
                ('auto_flagged', models.BooleanField(default=False)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-report_count'],
            },
        ),
    ]
